# Install script for directory: C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/src/osgPlugins

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/OpenSceneGraph")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "Release")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

IF(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/osgAnimation/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/osgFX/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/osgParticle/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/osgSim/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/osgText/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/osgViewer/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/osgShadow/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/osgTerrain/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/osgVolume/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/osgWidget/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/osga/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/rot/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/scale/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/trans/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/normals/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/osg/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/ive/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/cfg/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/glsl/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/rgb/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/bmp/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/pnm/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/dds/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/tga/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/hdr/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/dot/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/vtf/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/jpeg/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/gif/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/png/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/tiff/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/3dc/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/gz/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/lwo/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/bvh/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/x/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/dw/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/dxf/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/OpenFlight/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/geo/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/obj/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/pic/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/stl/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/3ds/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/ac/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/logo/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/lws/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/md2/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/osgtgz/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/tgz/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/shp/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/txf/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/bsp/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/mdl/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/ply/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/txp/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/freetype/cmake_install.cmake")
  INCLUDE("C:/Projects/AnimatLabSDK/AnimatLabPublicSource/Libraries/OpenSceneGraph-2.8.3/OsgBuild/src/osgPlugins/zip/cmake_install.cmake")

ENDIF(NOT CMAKE_INSTALL_LOCAL_ONLY)

