'------------------------------------------------------------------------------
'  <auto-generated>
'      This code was generated by coded UI test builder.
'      Version: 10.0.0.0
'
'      Changes to this file may cause incorrect behavior and will be lost if
'      the code is regenerated.
'  </auto-generated>
' ------------------------------------------------------------------------------

Imports System
Imports System.CodeDom.Compiler
Imports System.Collections.Generic
Imports System.Drawing
Imports System.Text.RegularExpressions
Imports System.Windows.Input
Imports Microsoft.VisualStudio.TestTools.UITest.Extension
Imports Microsoft.VisualStudio.TestTools.UITesting
Imports Microsoft.VisualStudio.TestTools.UITesting.WinControls
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard
Imports Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse
Imports MouseButtons = System.Windows.Forms.MouseButtons

Namespace AnimatTesting
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Partial Public Class UIMap
        
        '''<summary>
        '''NewProjectDlg_EnterNameAndPath - Use 'NewProjectDlg_EnterNameAndPathParams' to pass parameters into this method.
        '''</summary>
        Public Sub NewProjectDlg_EnterNameAndPath()
            Dim uITxtProjectNameEdit As WinEdit = Me.UINewProjectWindow.UINewProjectWindow1.UITxtProjectNameEdit
            Dim uITxtLocationEdit As WinEdit = Me.UINewProjectWindow.UITxtLocationWindow.UITxtLocationEdit
            Dim uIOKButton As WinButton = Me.UINewProjectWindow.UIOKWindow.UIOKButton

            'Type 'TestProject' in 'txtProjectName' text box
            uITxtProjectNameEdit.Text = Me.NewProjectDlg_EnterNameAndPathParams.UITxtProjectNameEditText

            'Type '{Tab}' in 'txtProjectName' text box
            Keyboard.SendKeys(uITxtProjectNameEdit, Me.NewProjectDlg_EnterNameAndPathParams.UITxtProjectNameEditSendKeys, ModifierKeys.None)

            'Type 'C:\Projects\AnimatLabSDK\Experiments' in 'txtLocation' text box
            uITxtLocationEdit.Text = Me.NewProjectDlg_EnterNameAndPathParams.UITxtLocationEditText

            'Click 'Ok' button
            Mouse.Click(uIOKButton, New Point(34, 15))
        End Sub
        
        '''<summary>
        '''AddRootPartType - Use 'AddRootPartTypeParams' to pass parameters into this method.
        '''</summary>
        Public Sub AddRootPartType()
            Dim uICtrlPartTypesList As WinList = Me.UISelectPartTypeWindow.UICtrlPartTypesWindow.UICtrlPartTypesList
            Dim uIOKButton As WinButton = Me.UISelectPartTypeWindow.UIOKWindow.UIOKButton

            'Select 'Box' in 'ctrlPartTypes' list box
            uICtrlPartTypesList.SelectedItemsAsString = Me.AddRootPartTypeParams.UICtrlPartTypesListSelectedItemsAsString

            'Click 'Ok' button
            Mouse.Click(uIOKButton, New Point(22, 10))
        End Sub
        
        '''<summary>
        '''AddChildPartTypeWithJoint - Use 'AddChildPartTypeWithJointParams' to pass parameters into this method.
        '''</summary>
        Public Sub AddChildPartTypeWithJoint()
            Dim uICtrlPartTypesList As WinList = Me.UISelectPartTypeWindow.UICtrlPartTypesWindow.UICtrlPartTypesList
            Dim uIOKButton As WinButton = Me.UISelectPartTypeWindow.UIOKWindow.UIOKButton

            'Select 'Box' in 'ctrlPartTypes' list box
            uICtrlPartTypesList.SelectedItemsAsString = Me.AddChildPartTypeWithJointParams.UICtrlPartTypesListSelectedItemsAsString

            'Click 'Ok' button
            Mouse.Click(uIOKButton, New Point(40, 9))

            'Select 'Hinge' in 'ctrlPartTypes' list box
            uICtrlPartTypesList.SelectedItemsAsString = Me.AddChildPartTypeWithJointParams.UICtrlPartTypesListSelectedItemsAsString1

            'Click 'Ok' button
            Mouse.Click(uIOKButton, New Point(45, 12))
        End Sub
        
        '''<summary>
        '''AddLineChart - Use 'AddLineChartParams' to pass parameters into this method.
        '''</summary>
        Public Sub AddLineChart()
            Dim uICtrlToolTypesList As WinList = Me.UISelectDataToolTypeWindow.UICtrlToolTypesWindow.UICtrlToolTypesList
            Dim uIOKButton As WinButton = Me.UISelectDataToolTypeWindow.UIOKWindow.UIOKButton

            'Select 'Line Chart' in 'ctrlToolTypes' list box
            uICtrlToolTypesList.SelectedItemsAsString = Me.AddLineChartParams.UICtrlToolTypesListSelectedItemsAsString

            'Click 'Ok' button
            Mouse.Click(uIOKButton, New Point(36, 14))
        End Sub
        
        '''<summary>
        '''AddRootPartToChart
        '''</summary>
        Public Sub AddRootPartToChart()
            Dim uITvStructuresClient As WinClient = Me.UISelectDataItemWindow.UITvStructuresWindow.UITvStructuresClient
            Dim uIOKButton As WinButton = Me.UISelectDataItemWindow.UIOKWindow.UIOKButton

            'Click 'tvStructures' client
            Mouse.Click(uITvStructuresClient, New Point(56, 26))

            'Click 'Ok' button
            Mouse.Click(uIOKButton, New Point(22, 8))
        End Sub
        
        '''<summary>
        '''AssertNewProjectAlreadyExists - Use 'AssertNewProjectAlreadyExistsExpectedValues' to pass parameters into this method.
        '''</summary>
        Public Sub AssertNewProjectAlreadyExists()
            Dim uITxtErrorMsgEdit As WinEdit = Me.UIErrorWindow.UIThedirectoryCProjectWindow.UITxtErrorMsgEdit

            'Verify that 'txtErrorMsg' text box's property 'Text' ends with '' already exists. Please choose a different name or location for the project.'
            StringAssert.EndsWith(uITxtErrorMsgEdit.Text, Me.AssertNewProjectAlreadyExistsExpectedValues.UITxtErrorMsgEditText)
        End Sub
        
        '''<summary>
        '''CloseNewProjectErrorWindow
        '''</summary>
        Public Sub CloseNewProjectErrorWindow()
            Dim uIOKButton As WinButton = Me.UIErrorWindow.UIOKWindow.UIOKButton
            Dim uICancelButton As WinButton = Me.UINewProjectWindow.UICancelWindow.UICancelButton

            'Click 'Ok' button
            Mouse.Click(uIOKButton, New Point(40, 11))

            'Click 'Cancel' button
            Mouse.Click(uICancelButton, New Point(38, 14))
        End Sub
        
        '''<summary>
        '''ZoomInOnRootPart
        '''</summary>
        Public Sub ZoomInOnRootPart()
            Dim uIStructure_1BodyClient As WinClient = Me.UIBoxTestProjectWindow.UIStructure_1BodyWindow.UIStructure_1BodyClient
            Dim uISimulationControllerClient As WinClient = Me.UIBoxTestProjectWindow.UIItemWindow.UIToolStripContainer1Client.UISimulationControllerClient

            'Move using Right button 'Structure_1 Body' client from (877, 353) to 'Simulation Controller' client (873, 12)
            uISimulationControllerClient.EnsureClickable(New Point(873, 12))
            Mouse.StartDragging(uIStructure_1BodyClient, New Point(877, 353), MouseButtons.Right, ModifierKeys.None)
            Mouse.StopDragging(uISimulationControllerClient, New Point(873, 12))

            'Move using Right button 'Structure_1 Body' client from (921, 203) to (922, 359)
            Mouse.StartDragging(uIStructure_1BodyClient, New Point(921, 203), MouseButtons.Right, ModifierKeys.None)
            Mouse.StopDragging(uIStructure_1BodyClient, 1, 156)
        End Sub
        
        '''<summary>
        '''OpenProject - Use 'OpenProjectParams' to pass parameters into this method.
        '''</summary>
        Public Sub OpenProject()
            Dim uIOpenButton As WinButton = Me.UIToolStripContainer1Window.UIAnimatToolStripWindow.UIOpenButton
            Dim uIAddressCProjectsAnimToolBar As WinToolBar = Me.UIOpenanAnimatLabProjeWindow.UIAddressCProjectsAnimWindow.UIAddressCProjectsAnimToolBar
            Dim uIAddressComboBox As WinComboBox = Me.UIOpenanAnimatLabProjeWindow.UIItemWindow.UIAddressComboBox
            Dim uIGotoCProjectsAnimatLButton As WinButton = Me.UIOpenanAnimatLabProjeWindow.UIItemWindow2.UIItemToolBar.UIGotoCProjectsAnimatLButton
            Dim uIFilenameComboBox As WinComboBox = Me.UIOpenanAnimatLabProjeWindow.UIItemWindow3.UIFilenameComboBox
            Dim uIOpenSplitButton As WinSplitButton = Me.UIOpenanAnimatLabProjeWindow.UIOpenWindow.UIOpenSplitButton

            'Click 'Open' button
            Mouse.Click(uIOpenButton, New Point(13, 12))

            'Click 'Address: C:\Projects\AnimatLabSDK\Experiments\Conv...' tool bar
            Mouse.Click(uIAddressCProjectsAnimToolBar, New Point(285, 9))

            'Select 'C:\Projects\AnimatLabSDK\AnimatLabPublicSource\Libraries\AnimatTesting\TestProjects\ConversionTests\BodyPartTests\JointTests\HingeTest' in 'Address' combo box
            uIAddressComboBox.EditableItem = Me.OpenProjectParams.UIAddressComboBoxEditableItem

            'Click 'Go to "C:\Projects\AnimatLabSDK\AnimatLabPublicSou...' button
            Mouse.Click(uIGotoCProjectsAnimatLButton, New Point(13, 10))

            'Select 'HingeTest.aproj' in 'File name:' combo box
            uIFilenameComboBox.EditableItem = Me.OpenProjectParams.UIFilenameComboBoxEditableItem

            'Click '&Open' split button
            Mouse.Click(uIOpenSplitButton, New Point(53, 12))
        End Sub
        
        #Region "Properties"
        Public Overridable ReadOnly Property NewProjectDlg_EnterNameAndPathParams() As NewProjectDlg_EnterNameAndPathParams
            Get
                If (Me.mNewProjectDlg_EnterNameAndPathParams Is Nothing) Then
                    Me.mNewProjectDlg_EnterNameAndPathParams = New NewProjectDlg_EnterNameAndPathParams()
                End If
                Return Me.mNewProjectDlg_EnterNameAndPathParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property AddRootPartTypeParams() As AddRootPartTypeParams
            Get
                If (Me.mAddRootPartTypeParams Is Nothing) Then
                    Me.mAddRootPartTypeParams = New AddRootPartTypeParams()
                End If
                Return Me.mAddRootPartTypeParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property AddChildPartTypeWithJointParams() As AddChildPartTypeWithJointParams
            Get
                If (Me.mAddChildPartTypeWithJointParams Is Nothing) Then
                    Me.mAddChildPartTypeWithJointParams = New AddChildPartTypeWithJointParams()
                End If
                Return Me.mAddChildPartTypeWithJointParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property AddLineChartParams() As AddLineChartParams
            Get
                If (Me.mAddLineChartParams Is Nothing) Then
                    Me.mAddLineChartParams = New AddLineChartParams()
                End If
                Return Me.mAddLineChartParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property AssertNewProjectAlreadyExistsExpectedValues() As AssertNewProjectAlreadyExistsExpectedValues
            Get
                If (Me.mAssertNewProjectAlreadyExistsExpectedValues Is Nothing) Then
                    Me.mAssertNewProjectAlreadyExistsExpectedValues = New AssertNewProjectAlreadyExistsExpectedValues()
                End If
                Return Me.mAssertNewProjectAlreadyExistsExpectedValues
            End Get
        End Property
        
        Public Overridable ReadOnly Property OpenProjectParams() As OpenProjectParams
            Get
                If (Me.mOpenProjectParams Is Nothing) Then
                    Me.mOpenProjectParams = New OpenProjectParams()
                End If
                Return Me.mOpenProjectParams
            End Get
        End Property
        
        Public ReadOnly Property UINewProjectWindow() As UINewProjectWindow
            Get
                If (Me.mUINewProjectWindow Is Nothing) Then
                    Me.mUINewProjectWindow = New UINewProjectWindow()
                End If
                Return Me.mUINewProjectWindow
            End Get
        End Property
        
        Public ReadOnly Property UISelectPartTypeWindow() As UISelectPartTypeWindow
            Get
                If (Me.mUISelectPartTypeWindow Is Nothing) Then
                    Me.mUISelectPartTypeWindow = New UISelectPartTypeWindow()
                End If
                Return Me.mUISelectPartTypeWindow
            End Get
        End Property
        
        Public ReadOnly Property UISelectDataToolTypeWindow() As UISelectDataToolTypeWindow
            Get
                If (Me.mUISelectDataToolTypeWindow Is Nothing) Then
                    Me.mUISelectDataToolTypeWindow = New UISelectDataToolTypeWindow()
                End If
                Return Me.mUISelectDataToolTypeWindow
            End Get
        End Property
        
        Public ReadOnly Property UISelectDataItemWindow() As UISelectDataItemWindow
            Get
                If (Me.mUISelectDataItemWindow Is Nothing) Then
                    Me.mUISelectDataItemWindow = New UISelectDataItemWindow()
                End If
                Return Me.mUISelectDataItemWindow
            End Get
        End Property
        
        Public ReadOnly Property UIErrorWindow() As UIErrorWindow
            Get
                If (Me.mUIErrorWindow Is Nothing) Then
                    Me.mUIErrorWindow = New UIErrorWindow()
                End If
                Return Me.mUIErrorWindow
            End Get
        End Property
        
        Public ReadOnly Property UIBoxTestProjectWindow() As UIBoxTestProjectWindow
            Get
                If (Me.mUIBoxTestProjectWindow Is Nothing) Then
                    Me.mUIBoxTestProjectWindow = New UIBoxTestProjectWindow()
                End If
                Return Me.mUIBoxTestProjectWindow
            End Get
        End Property
        
        Public ReadOnly Property UIToolStripContainer1Window() As UIToolStripContainer1Window
            Get
                If (Me.mUIToolStripContainer1Window Is Nothing) Then
                    Me.mUIToolStripContainer1Window = New UIToolStripContainer1Window()
                End If
                Return Me.mUIToolStripContainer1Window
            End Get
        End Property
        
        Public ReadOnly Property UIOpenanAnimatLabProjeWindow() As UIOpenanAnimatLabProjeWindow
            Get
                If (Me.mUIOpenanAnimatLabProjeWindow Is Nothing) Then
                    Me.mUIOpenanAnimatLabProjeWindow = New UIOpenanAnimatLabProjeWindow()
                End If
                Return Me.mUIOpenanAnimatLabProjeWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mNewProjectDlg_EnterNameAndPathParams As NewProjectDlg_EnterNameAndPathParams
        
        Private mAddRootPartTypeParams As AddRootPartTypeParams
        
        Private mAddChildPartTypeWithJointParams As AddChildPartTypeWithJointParams
        
        Private mAddLineChartParams As AddLineChartParams
        
        Private mAssertNewProjectAlreadyExistsExpectedValues As AssertNewProjectAlreadyExistsExpectedValues
        
        Private mOpenProjectParams As OpenProjectParams
        
        Private mUINewProjectWindow As UINewProjectWindow
        
        Private mUISelectPartTypeWindow As UISelectPartTypeWindow
        
        Private mUISelectDataToolTypeWindow As UISelectDataToolTypeWindow
        
        Private mUISelectDataItemWindow As UISelectDataItemWindow
        
        Private mUIErrorWindow As UIErrorWindow
        
        Private mUIBoxTestProjectWindow As UIBoxTestProjectWindow
        
        Private mUIToolStripContainer1Window As UIToolStripContainer1Window
        
        Private mUIOpenanAnimatLabProjeWindow As UIOpenanAnimatLabProjeWindow
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'NewProjectDlg_EnterNameAndPath'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class NewProjectDlg_EnterNameAndPathParams
        
        #Region "Fields"
        '''<summary>
        '''Type 'TestProject' in 'txtProjectName' text box
        '''</summary>
        Public UITxtProjectNameEditText As String = "TestProject"
        
        '''<summary>
        '''Type '{Tab}' in 'txtProjectName' text box
        '''</summary>
        Public UITxtProjectNameEditSendKeys As String = "{Tab}"
        
        '''<summary>
        '''Type 'C:\Projects\AnimatLabSDK\Experiments' in 'txtLocation' text box
        '''</summary>
        Public UITxtLocationEditText As String = "C:\Projects\AnimatLabSDK\Experiments"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'AddRootPartType'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class AddRootPartTypeParams
        
        #Region "Fields"
        '''<summary>
        '''Select 'Box' in 'ctrlPartTypes' list box
        '''</summary>
        Public UICtrlPartTypesListSelectedItemsAsString As String = "Box"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'AddChildPartTypeWithJoint'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class AddChildPartTypeWithJointParams
        
        #Region "Fields"
        '''<summary>
        '''Select 'Box' in 'ctrlPartTypes' list box
        '''</summary>
        Public UICtrlPartTypesListSelectedItemsAsString As String = "Box"
        
        '''<summary>
        '''Select 'Hinge' in 'ctrlPartTypes' list box
        '''</summary>
        Public UICtrlPartTypesListSelectedItemsAsString1 As String = "Hinge"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'AddLineChart'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class AddLineChartParams
        
        #Region "Fields"
        '''<summary>
        '''Select 'Line Chart' in 'ctrlToolTypes' list box
        '''</summary>
        Public UICtrlToolTypesListSelectedItemsAsString As String = "Line Chart"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'AssertNewProjectAlreadyExists'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class AssertNewProjectAlreadyExistsExpectedValues
        
        #Region "Fields"
        '''<summary>
        '''Verify that 'txtErrorMsg' text box's property 'Text' ends with '' already exists. Please choose a different name or location for the project.'
        '''</summary>
        Public UITxtErrorMsgEditText As String = "' already exists. Please choose a different name or location for the project."
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'OpenProject'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class OpenProjectParams
        
        #Region "Fields"
        '''<summary>
        '''Select 'C:\Projects\AnimatLabSDK\AnimatLabPublicSource\Libraries\AnimatTesting\TestProjects\ConversionTests\BodyPartTests\JointTests\HingeTest' in 'Address' combo box
        '''</summary>
        Public UIAddressComboBoxEditableItem As String = "C:\Projects\AnimatLabSDK\AnimatLabPublicSource\Libraries\AnimatTesting\TestProjec"& _ 
            "ts\ConversionTests\BodyPartTests\JointTests\HingeTest"
        
        '''<summary>
        '''Select 'HingeTest.aproj' in 'File name:' combo box
        '''</summary>
        Public UIFilenameComboBoxEditableItem As String = "HingeTest.aproj"
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UINewProjectWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "New Project"
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains))
            Me.WindowTitles.Add("New Project")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UINewProjectWindow1() As UINewProjectWindow1
            Get
                If (Me.mUINewProjectWindow1 Is Nothing) Then
                    Me.mUINewProjectWindow1 = New UINewProjectWindow1(Me)
                End If
                Return Me.mUINewProjectWindow1
            End Get
        End Property
        
        Public ReadOnly Property UITxtLocationWindow() As UITxtLocationWindow
            Get
                If (Me.mUITxtLocationWindow Is Nothing) Then
                    Me.mUITxtLocationWindow = New UITxtLocationWindow(Me)
                End If
                Return Me.mUITxtLocationWindow
            End Get
        End Property
        
        Public ReadOnly Property UIOKWindow() As UIOKWindow
            Get
                If (Me.mUIOKWindow Is Nothing) Then
                    Me.mUIOKWindow = New UIOKWindow(Me)
                End If
                Return Me.mUIOKWindow
            End Get
        End Property
        
        Public ReadOnly Property UICancelWindow() As UICancelWindow
            Get
                If (Me.mUICancelWindow Is Nothing) Then
                    Me.mUICancelWindow = New UICancelWindow(Me)
                End If
                Return Me.mUICancelWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUINewProjectWindow1 As UINewProjectWindow1
        
        Private mUITxtLocationWindow As UITxtLocationWindow
        
        Private mUIOKWindow As UIOKWindow
        
        Private mUICancelWindow As UICancelWindow
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UINewProjectWindow1
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "txtProjectName"
            Me.WindowTitles.Add("New Project")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UITxtProjectNameEdit() As WinEdit
            Get
                If (Me.mUITxtProjectNameEdit Is Nothing) Then
                    Me.mUITxtProjectNameEdit = New WinEdit(Me)
                    Me.mUITxtProjectNameEdit.SearchProperties(WinEdit.PropertyNames.Name) = "Location"
                    Me.mUITxtProjectNameEdit.WindowTitles.Add("New Project")
                End If
                Return Me.mUITxtProjectNameEdit
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUITxtProjectNameEdit As WinEdit
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UITxtLocationWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "txtLocation"
            Me.WindowTitles.Add("New Project")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UITxtLocationEdit() As WinEdit
            Get
                If (Me.mUITxtLocationEdit Is Nothing) Then
                    Me.mUITxtLocationEdit = New WinEdit(Me)
                    Me.mUITxtLocationEdit.WindowTitles.Add("New Project")
                End If
                Return Me.mUITxtLocationEdit
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUITxtLocationEdit As WinEdit
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIOKWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "btnOk"
            Me.WindowTitles.Add("New Project")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIOKButton() As WinButton
            Get
                If (Me.mUIOKButton Is Nothing) Then
                    Me.mUIOKButton = New WinButton(Me)
                    Me.mUIOKButton.SearchProperties(WinButton.PropertyNames.Name) = "Ok"
                    Me.mUIOKButton.WindowTitles.Add("New Project")
                End If
                Return Me.mUIOKButton
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIOKButton As WinButton
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UICancelWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "btnCancel"
            Me.WindowTitles.Add("New Project")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UICancelButton() As WinButton
            Get
                If (Me.mUICancelButton Is Nothing) Then
                    Me.mUICancelButton = New WinButton(Me)
                    Me.mUICancelButton.SearchProperties(WinButton.PropertyNames.Name) = "Cancel"
                    Me.mUICancelButton.WindowTitles.Add("New Project")
                End If
                Return Me.mUICancelButton
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUICancelButton As WinButton
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UISelectPartTypeWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "Select Part Type"
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains))
            Me.WindowTitles.Add("Select Part Type")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UICtrlPartTypesWindow() As UICtrlPartTypesWindow
            Get
                If (Me.mUICtrlPartTypesWindow Is Nothing) Then
                    Me.mUICtrlPartTypesWindow = New UICtrlPartTypesWindow(Me)
                End If
                Return Me.mUICtrlPartTypesWindow
            End Get
        End Property
        
        Public ReadOnly Property UIOKWindow() As UIOKWindow1
            Get
                If (Me.mUIOKWindow Is Nothing) Then
                    Me.mUIOKWindow = New UIOKWindow1(Me)
                End If
                Return Me.mUIOKWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUICtrlPartTypesWindow As UICtrlPartTypesWindow
        
        Private mUIOKWindow As UIOKWindow1
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UICtrlPartTypesWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "ctrlPartTypes"
            Me.WindowTitles.Add("Select Part Type")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UICtrlPartTypesList() As WinList
            Get
                If (Me.mUICtrlPartTypesList Is Nothing) Then
                    Me.mUICtrlPartTypesList = New WinList(Me)
                    Me.mUICtrlPartTypesList.WindowTitles.Add("Select Part Type")
                End If
                Return Me.mUICtrlPartTypesList
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUICtrlPartTypesList As WinList
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIOKWindow1
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "btnOk"
            Me.WindowTitles.Add("Select Part Type")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIOKButton() As WinButton
            Get
                If (Me.mUIOKButton Is Nothing) Then
                    Me.mUIOKButton = New WinButton(Me)
                    Me.mUIOKButton.SearchProperties(WinButton.PropertyNames.Name) = "Ok"
                    Me.mUIOKButton.WindowTitles.Add("Select Part Type")
                End If
                Return Me.mUIOKButton
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIOKButton As WinButton
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UISelectDataToolTypeWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "Select Data Tool Type"
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains))
            Me.WindowTitles.Add("Select Data Tool Type")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UICtrlToolTypesWindow() As UICtrlToolTypesWindow
            Get
                If (Me.mUICtrlToolTypesWindow Is Nothing) Then
                    Me.mUICtrlToolTypesWindow = New UICtrlToolTypesWindow(Me)
                End If
                Return Me.mUICtrlToolTypesWindow
            End Get
        End Property
        
        Public ReadOnly Property UIOKWindow() As UIOKWindow2
            Get
                If (Me.mUIOKWindow Is Nothing) Then
                    Me.mUIOKWindow = New UIOKWindow2(Me)
                End If
                Return Me.mUIOKWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUICtrlToolTypesWindow As UICtrlToolTypesWindow
        
        Private mUIOKWindow As UIOKWindow2
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UICtrlToolTypesWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "ctrlToolTypes"
            Me.WindowTitles.Add("Select Data Tool Type")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UICtrlToolTypesList() As WinList
            Get
                If (Me.mUICtrlToolTypesList Is Nothing) Then
                    Me.mUICtrlToolTypesList = New WinList(Me)
                    Me.mUICtrlToolTypesList.WindowTitles.Add("Select Data Tool Type")
                End If
                Return Me.mUICtrlToolTypesList
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUICtrlToolTypesList As WinList
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIOKWindow2
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "btnOk"
            Me.WindowTitles.Add("Select Data Tool Type")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIOKButton() As WinButton
            Get
                If (Me.mUIOKButton Is Nothing) Then
                    Me.mUIOKButton = New WinButton(Me)
                    Me.mUIOKButton.SearchProperties(WinButton.PropertyNames.Name) = "Ok"
                    Me.mUIOKButton.WindowTitles.Add("Select Data Tool Type")
                End If
                Return Me.mUIOKButton
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIOKButton As WinButton
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UISelectDataItemWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "Select Data Item"
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains))
            Me.WindowTitles.Add("Select Data Item")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UITvStructuresWindow() As UITvStructuresWindow
            Get
                If (Me.mUITvStructuresWindow Is Nothing) Then
                    Me.mUITvStructuresWindow = New UITvStructuresWindow(Me)
                End If
                Return Me.mUITvStructuresWindow
            End Get
        End Property
        
        Public ReadOnly Property UIOKWindow() As UIOKWindow3
            Get
                If (Me.mUIOKWindow Is Nothing) Then
                    Me.mUIOKWindow = New UIOKWindow3(Me)
                End If
                Return Me.mUIOKWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUITvStructuresWindow As UITvStructuresWindow
        
        Private mUIOKWindow As UIOKWindow3
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UITvStructuresWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "tvStructures"
            Me.WindowTitles.Add("Select Data Item")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UITvStructuresClient() As WinClient
            Get
                If (Me.mUITvStructuresClient Is Nothing) Then
                    Me.mUITvStructuresClient = New WinClient(Me)
                    Me.mUITvStructuresClient.WindowTitles.Add("Select Data Item")
                End If
                Return Me.mUITvStructuresClient
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUITvStructuresClient As WinClient
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIOKWindow3
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "btnOk"
            Me.WindowTitles.Add("Select Data Item")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIOKButton() As WinButton
            Get
                If (Me.mUIOKButton Is Nothing) Then
                    Me.mUIOKButton = New WinButton(Me)
                    Me.mUIOKButton.SearchProperties(WinButton.PropertyNames.Name) = "Ok"
                    Me.mUIOKButton.WindowTitles.Add("Select Data Item")
                End If
                Return Me.mUIOKButton
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIOKButton As WinButton
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIErrorWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "Error"
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains))
            Me.WindowTitles.Add("Error")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIThedirectoryCProjectWindow() As UIThedirectoryCProjectWindow
            Get
                If (Me.mUIThedirectoryCProjectWindow Is Nothing) Then
                    Me.mUIThedirectoryCProjectWindow = New UIThedirectoryCProjectWindow(Me)
                End If
                Return Me.mUIThedirectoryCProjectWindow
            End Get
        End Property
        
        Public ReadOnly Property UIOKWindow() As UIOKWindow4
            Get
                If (Me.mUIOKWindow Is Nothing) Then
                    Me.mUIOKWindow = New UIOKWindow4(Me)
                End If
                Return Me.mUIOKWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIThedirectoryCProjectWindow As UIThedirectoryCProjectWindow
        
        Private mUIOKWindow As UIOKWindow4
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIThedirectoryCProjectWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "txtErrorMsg"
            Me.WindowTitles.Add("Error")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UITxtErrorMsgEdit() As WinEdit
            Get
                If (Me.mUITxtErrorMsgEdit Is Nothing) Then
                    Me.mUITxtErrorMsgEdit = New WinEdit(Me)
                    Me.mUITxtErrorMsgEdit.WindowTitles.Add("Error")
                End If
                Return Me.mUITxtErrorMsgEdit
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUITxtErrorMsgEdit As WinEdit
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIOKWindow4
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "btnOk"
            Me.WindowTitles.Add("Error")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIOKButton() As WinButton
            Get
                If (Me.mUIOKButton Is Nothing) Then
                    Me.mUIOKButton = New WinButton(Me)
                    Me.mUIOKButton.SearchProperties(WinButton.PropertyNames.Name) = "Ok"
                    Me.mUIOKButton.WindowTitles.Add("Error")
                End If
                Return Me.mUIOKButton
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIOKButton As WinButton
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIBoxTestProjectWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "BoxTest Project *"
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains))
            Me.WindowTitles.Add("BoxTest Project *")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIStructure_1BodyWindow() As UIStructure_1BodyWindow
            Get
                If (Me.mUIStructure_1BodyWindow Is Nothing) Then
                    Me.mUIStructure_1BodyWindow = New UIStructure_1BodyWindow(Me)
                End If
                Return Me.mUIStructure_1BodyWindow
            End Get
        End Property
        
        Public ReadOnly Property UIItemWindow() As UIItemWindow
            Get
                If (Me.mUIItemWindow Is Nothing) Then
                    Me.mUIItemWindow = New UIItemWindow(Me)
                End If
                Return Me.mUIItemWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIStructure_1BodyWindow As UIStructure_1BodyWindow
        
        Private mUIItemWindow As UIItemWindow
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIStructure_1BodyWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "SimulationWindow_Toolstrips"
            Me.WindowTitles.Add("BoxTest Project *")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIStructure_1BodyClient() As WinClient
            Get
                If (Me.mUIStructure_1BodyClient Is Nothing) Then
                    Me.mUIStructure_1BodyClient = New WinClient(Me)
                    Me.mUIStructure_1BodyClient.SearchProperties(WinControl.PropertyNames.Name) = "Structure_1 Body"
                    Me.mUIStructure_1BodyClient.WindowTitles.Add("BoxTest Project *")
                End If
                Return Me.mUIStructure_1BodyClient
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIStructure_1BodyClient As WinClient
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIItemWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains))
            Me.SearchProperties(WinWindow.PropertyNames.Instance) = "10"
            Me.WindowTitles.Add("BoxTest Project *")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIToolStripContainer1Client() As UIToolStripContainer1Client
            Get
                If (Me.mUIToolStripContainer1Client Is Nothing) Then
                    Me.mUIToolStripContainer1Client = New UIToolStripContainer1Client(Me)
                End If
                Return Me.mUIToolStripContainer1Client
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIToolStripContainer1Client As UIToolStripContainer1Client
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIToolStripContainer1Client
        Inherits WinClient
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.WindowTitles.Add("BoxTest Project *")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UISimulationControllerClient() As WinClient
            Get
                If (Me.mUISimulationControllerClient Is Nothing) Then
                    Me.mUISimulationControllerClient = New WinClient(Me)
                    Me.mUISimulationControllerClient.SearchProperties(WinControl.PropertyNames.Name) = "Simulation Controller"
                    Me.mUISimulationControllerClient.WindowTitles.Add("BoxTest Project *")
                End If
                Return Me.mUISimulationControllerClient
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUISimulationControllerClient As WinClient
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIToolStripContainer1Window
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "ToolStripContainer1"
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains))
            Me.WindowTitles.Add("ToolStripContainer1")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIAnimatToolStripWindow() As UIAnimatToolStripWindow
            Get
                If (Me.mUIAnimatToolStripWindow Is Nothing) Then
                    Me.mUIAnimatToolStripWindow = New UIAnimatToolStripWindow(Me)
                End If
                Return Me.mUIAnimatToolStripWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIAnimatToolStripWindow As UIAnimatToolStripWindow
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIAnimatToolStripWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "AnimatToolStrip"
            Me.WindowTitles.Add("ToolStripContainer1")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIOpenButton() As WinButton
            Get
                If (Me.mUIOpenButton Is Nothing) Then
                    Me.mUIOpenButton = New WinButton(Me)
                    Me.mUIOpenButton.SearchProperties(WinButton.PropertyNames.Name) = "Open"
                    Me.mUIOpenButton.WindowTitles.Add("ToolStripContainer1")
                End If
                Return Me.mUIOpenButton
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIOpenButton As WinButton
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIOpenanAnimatLabProjeWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "Open an AnimatLab Project"
            Me.SearchProperties(WinWindow.PropertyNames.ClassName) = "#32770"
            Me.WindowTitles.Add("Open an AnimatLab Project")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIAddressCProjectsAnimWindow() As UIAddressCProjectsAnimWindow
            Get
                If (Me.mUIAddressCProjectsAnimWindow Is Nothing) Then
                    Me.mUIAddressCProjectsAnimWindow = New UIAddressCProjectsAnimWindow(Me)
                End If
                Return Me.mUIAddressCProjectsAnimWindow
            End Get
        End Property
        
        Public ReadOnly Property UIItemWindow() As UIItemWindow1
            Get
                If (Me.mUIItemWindow Is Nothing) Then
                    Me.mUIItemWindow = New UIItemWindow1(Me)
                End If
                Return Me.mUIItemWindow
            End Get
        End Property
        
        Public ReadOnly Property UIItemWindow2() As UIItemWindow2
            Get
                If (Me.mUIItemWindow2 Is Nothing) Then
                    Me.mUIItemWindow2 = New UIItemWindow2(Me)
                End If
                Return Me.mUIItemWindow2
            End Get
        End Property
        
        Public ReadOnly Property UIItemWindow3() As UIItemWindow3
            Get
                If (Me.mUIItemWindow3 Is Nothing) Then
                    Me.mUIItemWindow3 = New UIItemWindow3(Me)
                End If
                Return Me.mUIItemWindow3
            End Get
        End Property
        
        Public ReadOnly Property UIOpenWindow() As UIOpenWindow
            Get
                If (Me.mUIOpenWindow Is Nothing) Then
                    Me.mUIOpenWindow = New UIOpenWindow(Me)
                End If
                Return Me.mUIOpenWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIAddressCProjectsAnimWindow As UIAddressCProjectsAnimWindow
        
        Private mUIItemWindow As UIItemWindow1
        
        Private mUIItemWindow2 As UIItemWindow2
        
        Private mUIItemWindow3 As UIItemWindow3
        
        Private mUIOpenWindow As UIOpenWindow
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIAddressCProjectsAnimWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlId) = "1001"
            Me.WindowTitles.Add("Open an AnimatLab Project")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIAddressCProjectsAnimToolBar() As WinToolBar
            Get
                If (Me.mUIAddressCProjectsAnimToolBar Is Nothing) Then
                    Me.mUIAddressCProjectsAnimToolBar = New WinToolBar(Me)
                    Me.mUIAddressCProjectsAnimToolBar.SearchProperties(WinToolBar.PropertyNames.Name) = "Address: C:\Projects\AnimatLabSDK\Experiments\ConversionTests\OldVersion\HingeTes"& _ 
                        "tNew\Backup"
                    Me.mUIAddressCProjectsAnimToolBar.WindowTitles.Add("Open an AnimatLab Project")
                End If
                Return Me.mUIAddressCProjectsAnimToolBar
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIAddressCProjectsAnimToolBar As WinToolBar
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIItemWindow1
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlId) = "41477"
            Me.SearchProperties(WinWindow.PropertyNames.Instance) = "3"
            Me.WindowTitles.Add("Open an AnimatLab Project")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIAddressComboBox() As WinComboBox
            Get
                If (Me.mUIAddressComboBox Is Nothing) Then
                    Me.mUIAddressComboBox = New WinComboBox(Me)
                    Me.mUIAddressComboBox.SearchProperties(WinComboBox.PropertyNames.Name) = "Address"
                    Me.mUIAddressComboBox.WindowTitles.Add("Open an AnimatLab Project")
                End If
                Return Me.mUIAddressComboBox
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIAddressComboBox As WinComboBox
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIItemWindow2
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ClassName) = "ToolbarWindow32"
            Me.SearchProperties(WinWindow.PropertyNames.Instance) = "2"
            Me.WindowTitles.Add("Open an AnimatLab Project")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIItemToolBar() As UIItemToolBar
            Get
                If (Me.mUIItemToolBar Is Nothing) Then
                    Me.mUIItemToolBar = New UIItemToolBar(Me)
                End If
                Return Me.mUIItemToolBar
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIItemToolBar As UIItemToolBar
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIItemToolBar
        Inherits WinToolBar
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.WindowTitles.Add("Open an AnimatLab Project")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIGotoCProjectsAnimatLButton() As WinButton
            Get
                If (Me.mUIGotoCProjectsAnimatLButton Is Nothing) Then
                    Me.mUIGotoCProjectsAnimatLButton = New WinButton(Me)
                    Me.mUIGotoCProjectsAnimatLButton.SearchProperties(WinButton.PropertyNames.Name) = "Go to ""C:\Projects\AnimatLabSDK\AnimatLabPublicSource\Libraries\AnimatTesting\Tes"& _ 
                        "tProjects\ConversionTests\BodyPartTests\JointTests\HingeTest"""
                    Me.mUIGotoCProjectsAnimatLButton.WindowTitles.Add("Open an AnimatLab Project")
                End If
                Return Me.mUIGotoCProjectsAnimatLButton
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIGotoCProjectsAnimatLButton As WinButton
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIItemWindow3
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlId) = "1148"
            Me.SearchProperties(WinWindow.PropertyNames.Instance) = "2"
            Me.WindowTitles.Add("Open an AnimatLab Project")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIFilenameComboBox() As WinComboBox
            Get
                If (Me.mUIFilenameComboBox Is Nothing) Then
                    Me.mUIFilenameComboBox = New WinComboBox(Me)
                    Me.mUIFilenameComboBox.SearchProperties(WinComboBox.PropertyNames.Name) = "File name:"
                    Me.mUIFilenameComboBox.WindowTitles.Add("Open an AnimatLab Project")
                End If
                Return Me.mUIFilenameComboBox
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIFilenameComboBox As WinComboBox
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIOpenWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlId) = "1"
            Me.WindowTitles.Add("Open an AnimatLab Project")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIOpenSplitButton() As WinSplitButton
            Get
                If (Me.mUIOpenSplitButton Is Nothing) Then
                    Me.mUIOpenSplitButton = New WinSplitButton(Me)
                    Me.mUIOpenSplitButton.SearchProperties(WinButton.PropertyNames.Name) = "Open"
                    Me.mUIOpenSplitButton.WindowTitles.Add("Open an AnimatLab Project")
                End If
                Return Me.mUIOpenSplitButton
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIOpenSplitButton As WinSplitButton
        #End Region
    End Class
End Namespace
