//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crownwood.DotNetMagic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crownwood.DotNetMagic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BlackButtonCloseA {
            get {
                object obj = ResourceManager.GetObject("BlackButtonCloseA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlackButtonCloseAH {
            get {
                object obj = ResourceManager.GetObject("BlackButtonCloseAH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlackButtonCloseI {
            get {
                object obj = ResourceManager.GetObject("BlackButtonCloseI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlackButtonMaxA {
            get {
                object obj = ResourceManager.GetObject("BlackButtonMaxA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlackButtonMaxAH {
            get {
                object obj = ResourceManager.GetObject("BlackButtonMaxAH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlackButtonMaxI {
            get {
                object obj = ResourceManager.GetObject("BlackButtonMaxI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlackButtonMinA {
            get {
                object obj = ResourceManager.GetObject("BlackButtonMinA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlackButtonMinAH {
            get {
                object obj = ResourceManager.GetObject("BlackButtonMinAH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlackButtonMinI {
            get {
                object obj = ResourceManager.GetObject("BlackButtonMinI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlackButtonPressed {
            get {
                object obj = ResourceManager.GetObject("BlackButtonPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlackButtonPressedS {
            get {
                object obj = ResourceManager.GetObject("BlackButtonPressedS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlackButtonRestoreA {
            get {
                object obj = ResourceManager.GetObject("BlackButtonRestoreA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlackButtonRestoreAH {
            get {
                object obj = ResourceManager.GetObject("BlackButtonRestoreAH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlackButtonRestoreI {
            get {
                object obj = ResourceManager.GetObject("BlackButtonRestoreI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlackButtonTracking {
            get {
                object obj = ResourceManager.GetObject("BlackButtonTracking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlackButtonTrackingS {
            get {
                object obj = ResourceManager.GetObject("BlackButtonTrackingS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlackCaptionA {
            get {
                object obj = ResourceManager.GetObject("BlackCaptionA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlackCaptionI {
            get {
                object obj = ResourceManager.GetObject("BlackCaptionI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueButtonCloseA {
            get {
                object obj = ResourceManager.GetObject("BlueButtonCloseA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueButtonCloseI {
            get {
                object obj = ResourceManager.GetObject("BlueButtonCloseI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueButtonMaxA {
            get {
                object obj = ResourceManager.GetObject("BlueButtonMaxA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueButtonMaxI {
            get {
                object obj = ResourceManager.GetObject("BlueButtonMaxI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueButtonMinA {
            get {
                object obj = ResourceManager.GetObject("BlueButtonMinA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueButtonMinI {
            get {
                object obj = ResourceManager.GetObject("BlueButtonMinI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueButtonPressed {
            get {
                object obj = ResourceManager.GetObject("BlueButtonPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueButtonPressedS {
            get {
                object obj = ResourceManager.GetObject("BlueButtonPressedS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueButtonRestoreA {
            get {
                object obj = ResourceManager.GetObject("BlueButtonRestoreA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueButtonRestoreI {
            get {
                object obj = ResourceManager.GetObject("BlueButtonRestoreI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueButtonTracking {
            get {
                object obj = ResourceManager.GetObject("BlueButtonTracking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueButtonTrackingS {
            get {
                object obj = ResourceManager.GetObject("BlueButtonTrackingS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueCaptionA {
            get {
                object obj = ResourceManager.GetObject("BlueCaptionA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueCaptionI {
            get {
                object obj = ResourceManager.GetObject("BlueCaptionI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SilverButtonCloseA {
            get {
                object obj = ResourceManager.GetObject("SilverButtonCloseA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SilverButtonCloseI {
            get {
                object obj = ResourceManager.GetObject("SilverButtonCloseI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SilverButtonMaxA {
            get {
                object obj = ResourceManager.GetObject("SilverButtonMaxA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SilverButtonMaxI {
            get {
                object obj = ResourceManager.GetObject("SilverButtonMaxI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SilverButtonMinA {
            get {
                object obj = ResourceManager.GetObject("SilverButtonMinA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SilverButtonMinI {
            get {
                object obj = ResourceManager.GetObject("SilverButtonMinI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SilverButtonPressed {
            get {
                object obj = ResourceManager.GetObject("SilverButtonPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SilverButtonPressedS {
            get {
                object obj = ResourceManager.GetObject("SilverButtonPressedS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SilverButtonRestoreA {
            get {
                object obj = ResourceManager.GetObject("SilverButtonRestoreA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SilverButtonRestoreI {
            get {
                object obj = ResourceManager.GetObject("SilverButtonRestoreI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SilverButtonTracking {
            get {
                object obj = ResourceManager.GetObject("SilverButtonTracking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SilverButtonTrackingS {
            get {
                object obj = ResourceManager.GetObject("SilverButtonTrackingS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SilverCaptionA {
            get {
                object obj = ResourceManager.GetObject("SilverCaptionA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SilverCaptionI {
            get {
                object obj = ResourceManager.GetObject("SilverCaptionI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SparkleButtonBluePressed {
            get {
                object obj = ResourceManager.GetObject("SparkleButtonBluePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SparkleButtonBluePressedS {
            get {
                object obj = ResourceManager.GetObject("SparkleButtonBluePressedS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SparkleButtonCloseA {
            get {
                object obj = ResourceManager.GetObject("SparkleButtonCloseA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SparkleButtonCloseI {
            get {
                object obj = ResourceManager.GetObject("SparkleButtonCloseI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SparkleButtonMaxA {
            get {
                object obj = ResourceManager.GetObject("SparkleButtonMaxA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SparkleButtonMaxI {
            get {
                object obj = ResourceManager.GetObject("SparkleButtonMaxI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SparkleButtonMinA {
            get {
                object obj = ResourceManager.GetObject("SparkleButtonMinA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SparkleButtonMinI {
            get {
                object obj = ResourceManager.GetObject("SparkleButtonMinI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SparkleButtonOrangePressed {
            get {
                object obj = ResourceManager.GetObject("SparkleButtonOrangePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SparkleButtonOrangePressedS {
            get {
                object obj = ResourceManager.GetObject("SparkleButtonOrangePressedS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SparkleButtonPurplePressed {
            get {
                object obj = ResourceManager.GetObject("SparkleButtonPurplePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SparkleButtonPurplePressedS {
            get {
                object obj = ResourceManager.GetObject("SparkleButtonPurplePressedS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SparkleButtonRestoreA {
            get {
                object obj = ResourceManager.GetObject("SparkleButtonRestoreA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SparkleButtonRestoreI {
            get {
                object obj = ResourceManager.GetObject("SparkleButtonRestoreI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SparkleButtonTracking {
            get {
                object obj = ResourceManager.GetObject("SparkleButtonTracking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SparkleButtonTrackingS {
            get {
                object obj = ResourceManager.GetObject("SparkleButtonTrackingS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SparkleGrayChecked {
            get {
                object obj = ResourceManager.GetObject("SparkleGrayChecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SparkleGrayIndeterminate {
            get {
                object obj = ResourceManager.GetObject("SparkleGrayIndeterminate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
