'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class ModuleInformation
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AnimatGUI.ModuleInformation", GetType(ModuleInformation).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    Friend Shared ReadOnly Property AddDataTool() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("AddDataTool", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property AddOrganism() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("AddOrganism", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property AddOrganism1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("AddOrganism1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property AddStimulus() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("AddStimulus", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property AddStructure() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("AddStructure", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Delete() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Delete", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Equals() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Equals", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ExportStandalone() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ExportStandalone", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property HelpContents() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("HelpContents", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property HelpIndex() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("HelpIndex", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property HelpSearch() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("HelpSearch", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Redo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Redo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Relabel() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Relabel", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RelabelSelected() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RelabelSelected", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property SelectByType() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("SelectByType", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Simulate() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Simulate", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property TechnicalSupport() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("TechnicalSupport", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Undo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Undo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
End Class
