
	project "Bullet_UnitTests_x64"
		language "C++"
		kind     "ConsoleApp"
		files  { "../Bullet_UnitTests/*.h",
				 "../Bullet_UnitTests/*.cpp"}
		
		configuration { "Debug_x64", "windows" }
			includedirs { "../../../include",
						  "../../../../3rdParty/OpenSceneGraph-3.0.1_x64/include",
						  "../../../../3rdParty/osgWorks_03_00_00/include",
						  "../../../../3rdParty/Bullet-2.82/src",
						  "../../../../3rdParty/osgBullet_03_00_00/include",
						  "../../StdUtils",
						  "../../AnimatSim",
						  "../../OsgAnimatSim",
						  "../../BulletAnimatSim",
						  "../../../../3rdParty/boost_1_54_0"}	  
			libdirs { "../../../lib",
					  "$(OutDir)",
					  "../../../../3rdParty/OpenSceneGraph-3.0.1_x64/lib",
					  "../../../../3rdParty/osgWorks_03_00_00/lib",
					  "../../../../3rdParty/Bullet-2.82/lib",
					  "../../../../3rdParty/osgBullet_03_00_00/lib", 
					  "../../../../3rdParty/boost_1_54_0/lib_x64" }
			targetdir ("../../../bin_x64")
			targetname ("Bullet_UnitTests_single")
			defines { "WIN32", "_DEBUG", "_WINDOWS", "_USRDLL", "OSGBULLET_STATIC", "_CRT_SECURE_NO_WARNINGS"	}
			flags   { "Symbols", "SEH" }
			links { "OpenThreadsd", 
					"osgAnimationd", 
					"osgd", 
					"osgDBd", 
					"osgFXd", 
					"osgGAd", 
					"osgManipulatord", 
					"osgParticled", 
					"osgShadowd", 
					"osgSimd", 
					"osgTerraind", 
					"osgTextd", 
					"osgUtild", 
					"osgViewerd", 
					"osgVolumed", 
					"osgWidgetd", 
					"opengl32", 
					"osgbDynamicsd_single_x64",
					"osgbCollisiond_single_x64",
					"osgwControlsd",
					"osgwQueryd",
					"osgwToolsd",
					"BulletDynamics_vs2010_single_x64_debug",
					"BulletCollision_vs2010_single_x64_debug",
					"LinearMath_vs2010_single_x64_debug",
					"BulletSoftBody_vs2010_single_x64_debug",
					"wsock32", 
					"netapi32", 
					"comctl32", 
					"wbemuuid" }
					
		configuration { "Debug_Double_x64", "windows" }
			includedirs { "../../../include",
						  "../../../../3rdParty/OpenSceneGraph-3.0.1_x64/include",
						  "../../../../3rdParty/osgWorks_03_00_00/include",
						  "../../../../3rdParty/Bullet-2.82/src",
						  "../../../../3rdParty/osgBullet_03_00_00/include",
						  "../../StdUtils",
						  "../../AnimatSim",
						  "../../OsgAnimatSim",
						  "../../BulletAnimatSim",
						  "../../../../3rdParty/boost_1_54_0"}	  
			libdirs { "../../../lib",
					  "$(OutDir)",
					  "../../../../3rdParty/OpenSceneGraph-3.0.1_x64/lib",
					  "../../../../3rdParty/osgWorks_03_00_00/lib",
					  "../../../../3rdParty/Bullet-2.82/lib",
					  "../../../../3rdParty/osgBullet_03_00_00/lib", 
					  "../../../../3rdParty/boost_1_54_0/lib_x64" }
			targetdir ("../../../bin_x64")
			targetname ("Bullet_UnitTests_double")
			defines { "WIN32", "_DEBUG", "_WINDOWS", "_USRDLL", "OSGBULLET_STATIC", "_CRT_SECURE_NO_WARNINGS"	}
			flags   { "Symbols", "SEH" }
			links { "OpenThreadsd", 
					"osgAnimationd", 
					"osgd", 
					"osgDBd", 
					"osgFXd", 
					"osgGAd", 
					"osgManipulatord", 
					"osgParticled", 
					"osgShadowd", 
					"osgSimd", 
					"osgTerraind", 
					"osgTextd", 
					"osgUtild", 
					"osgViewerd", 
					"osgVolumed", 
					"osgWidgetd", 
					"opengl32", 
					"osgbDynamicsd_double_x64",
					"osgbCollisiond_double_x64",
					"osgwControlsd",
					"osgwQueryd",
					"osgwToolsd",
					"BulletDynamics_vs2010_double_x64_debug",
					"BulletCollision_vs2010_double_x64_debug",
					"LinearMath_vs2010_double_x64_debug",
					"BulletSoftBody_vs2010_double_x64_debug",
					"wsock32", 
					"netapi32", 
					"comctl32", 
					"wbemuuid" }	 
	 
		configuration { "Release_x64", "windows" }
			includedirs { "../../../include",
						  "../../../../3rdParty/OpenSceneGraph-3.0.1_x64/include",
						  "../../../../3rdParty/osgWorks_03_00_00/include",
						  "../../../../3rdParty/Bullet-2.82/src",
						  "../../../../3rdParty/osgBullet_03_00_00/include",
						  "../../StdUtils",
						  "../../AnimatSim",
						  "../../OsgAnimatSim",
						  "../../BulletAnimatSim",
						  "../../../../3rdParty/boost_1_54_0"}	  
			libdirs { "../../../lib",
					  "$(OutDir)",
					  "../../../../3rdParty/OpenSceneGraph-3.0.1_x64/lib",
					  "../../../../3rdParty/osgWorks_03_00_00/lib",
					  "../../../../3rdParty/Bullet-2.82/lib",
					  "../../../../3rdParty/osgBullet_03_00_00/lib", 
					  "../../../../3rdParty/boost_1_54_0/lib_x64" }
			targetdir ("../../../bin_x64")
			targetname ("Bullet_UnitTests_single")
			defines { "WIN32", "NDEBUG", "_WINDOWS", "_USRDLL", "OSGBULLET_STATIC" }
			flags   { "Optimize", "SEH" }
			links { "OpenThreads",
					"osgAnimation",
					"osg",
					"osgDB",
					"osgFX",
					"osgGA",
					"osgManipulator",
					"osgParticle",
					"osgShadow",
					"osgSim",
					"osgTerrain",
					"osgText",
					"osgUtil",
					"osgViewer",
					"osgVolume",
					"osgWidget",
					"opengl32",
					"osgbDynamics_single_x64",
					"osgbCollision_single_x64",
					"osgwControls",
					"osgwQuery",
					"osgwTools",
					"BulletDynamics_vs2010_x64_single",
					"BulletCollision_vs2010_x64_single",
					"LinearMath_vs2010_x64_single",
					"BulletSoftBody_vs2010_x64_single",
					"wsock32",
					"netapi32",
					"comctl32",
					"wbemuuid" }
					
		configuration { "Release_Double_x64", "windows" }
			includedirs { "../../../include",
						  "../../../../3rdParty/OpenSceneGraph-3.0.1_x64/include",
						  "../../../../3rdParty/osgWorks_03_00_00/include",
						  "../../../../3rdParty/Bullet-2.82/src",
						  "../../../../3rdParty/osgBullet_03_00_00/include",
						  "../../StdUtils",
						  "../../AnimatSim",
						  "../../OsgAnimatSim",
						  "../../BulletAnimatSim",
						  "../../../../3rdParty/boost_1_54_0"}	  
			libdirs { "../../../lib",
					  "$(OutDir)",
					  "../../../../3rdParty/OpenSceneGraph-3.0.1_x64/lib",
					  "../../../../3rdParty/osgWorks_03_00_00/lib",
					  "../../../../3rdParty/Bullet-2.82/lib",
					  "../../../../3rdParty/osgBullet_03_00_00/lib", 
					  "../../../../3rdParty/boost_1_54_0/lib_x64" }
			targetdir ("../../../bin_x64")
			targetname ("Bullet_UnitTests_double_x64")
			defines { "WIN32", "NDEBUG", "_WINDOWS", "_USRDLL", "OSGBULLET_STATIC" }
			flags   { "Optimize", "SEH" }
			links { "OpenThreads",
					"osgAnimation",
					"osg",
					"osgDB",
					"osgFX",
					"osgGA",
					"osgManipulator",
					"osgParticle",
					"osgShadow",
					"osgSim",
					"osgTerrain",
					"osgText",
					"osgUtil",
					"osgViewer",
					"osgVolume",
					"osgWidget",
					"opengl32",
					"osgbDynamics_double_x64",
					"osgbCollision_double_x64",
					"osgwControls",
					"osgwQuery",
					"osgwTools",
					"BulletDynamics_vs2010_double_x64",
					"BulletCollision_vs2010_double_x64",
					"LinearMath_vs2010_double_x64",
					"BulletSoftBody_vs2010_double_x64",
					"wsock32",
					"netapi32",
					"comctl32",
					"wbemuuid" }
